# Generated by Django 5.2.1 on 2025-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
