# Generated by Django 5.2.1 on 2025-06-17 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='action',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
